name: my_personal_portifolio
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  animated_text_kit: ^4.2.2
  custom_refresh_indicator: ^3.1.0
  fast_cached_network_image: ^1.2.9
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_localizations:
    sdk: flutter
  flutter_vibrate: ^1.3.0
  gap: ^3.0.1
  gif_view: ^0.4.3
  loading_animation_widget: ^1.2.1
  toastification: ^1.2.1
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/gifs/
    - assets/images/

  fonts:
    - family: Press Start 2P
      fonts:
        - asset: assets/fonts/PressStart2P-Regular.ttf
        
    - family: Sahitya
      fonts:
        - asset: assets/fonts/Sahitya-Regular.ttf
          weight: 400
        - asset: assets/fonts/Sahitya-Bold.ttf
          weight: 700